version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}
  mysql_data: {}

services:

# app runtime
# Laravel RR

  laravel-rr:
    build:
      context: laravel
      dockerfile: ../docker/Dockerfile
    ports:
      - '8080:8000'
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    mem_limit: 1024m
    cpus: 1.0

# app backend

  mysql:
    image: mysql:8.1.0
    ports:
      - 3306
    volumes:
      - ${APP_PATH-.}/docker/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      TZ: ${TZ-Asia/Tokyo}
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-time-zone=Asia/Tokyo

  redis:
    image: redis:6.0.16-alpine
    ports:
      - 6379
    environment:
      TZ: ${TZ-Asia/Tokyo}
